import Head from 'next/head'
import React, { FC } from 'react'
import { Navbar } from '../Navbar'
import styles from './MainLayout.module.css'

interface Props {
  children: React.ReactNode
}

const MainLayout: FC<Props> = ({children}) => {
  return (
    <main className={styles.main}>
      <Head>
        <title>Gliscano - Guillermo Rojas</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </main>
  )
}

export default MainLayout